### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by SwitWu** [BeautyLaTeX/latex-template#3]
嗯，在这里谈谈你这个模版的一些问题：

1. 文档类文件名最好不要加版本号，一是用户用起来麻烦，二是将来的每次版本更新会导致用户需要更改源代码，建议直接取名为 `Beautybook.cls`
2. 手册存在一些格式问题：
 
    + 标点符号的问题![1](https://github.com/BeautyLaTeX/latex-template/assets/39337667/5dc36440-e27f-484c-a3ba-844cfe22adf1)
    + 1.1.1 节 xelatex 和 lualatex 都叫做命令而不是引擎
    + 标点符号后面需要加空格，例如<img width="1184" alt="image" src="https://github.com/BeautyLaTeX/latex-template/assets/39337667/a63bfde1-8655-46b5-81d1-e73cf7ac5fc7">
    + 自相矛盾的点<img width="1258" alt="image" src="https://github.com/BeautyLaTeX/latex-template/assets/39337667/088580ac-e5fd-4590-9a52-562a147e8738">
    + 标点符号不统一，一些地方使用英文句号，一些地方使用中文句号

3. 仓库使用混乱，一个仓库只用于存储一个项目，便于管理和用户查阅。

**Comment by BeautyLaTeX** [comment]
好的，真诚地感谢您的建议！手册过于混乱的问题其实一直有关注的，但因为已经是最后的几天维护期了，所以还没能写好，到7月5日左右的时候会发布全新的手册，敬请关注。对于您提到的版本号混乱的问题，由于这是最终的版本了，所以理论上不存在混淆问题，除非您是看到了我的很多前期版本，所以这个很抱歉，不能做更改，因为这个版本号有一定的纪念意义，所以往后都不会有更新了，如果您实在介意的话，可以自行修改哈。无论怎样，真诚地感激您的提议，谢谢！
